In [1]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [3]:
from keras_preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts([text])
encoded = t.texts_to_sequences([text])[0]

In [34]:
vocab_size = len(t.word_index) + 1

In [43]:
print("단어 집합의 크기: %d" % vocab_size)

단어 집합의 크기: 12


In [19]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [20]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[: i+1]
        sequences.append(sequence)
print("훈련 데이터 개수: %d" % len(sequences))

훈련 데이터 개수: 11


In [21]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [22]:
print(max(len(l) for l in sequences))

6


In [27]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
sequences = pad_sequences(sequences, maxlen = 6, padding='pre')

C:\Users\515-15\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\515-15\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\515-15\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\515-15\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: P

In [28]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [29]:
import numpy as np
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

In [30]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [31]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [36]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab_size)

In [37]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [44]:
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN
from tensorflow.keras.models import Sequential

In [45]:
model = Sequential()

In [46]:
model.add(Embedding(vocab_size, 10, input_length=5))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Epoch 1/200
11/11 - 0s - loss: 2.5049 - acc: 0.0000e+00
Epoch 2/200
11/11 - 0s - loss: 2.4926 - acc: 0.0000e+00
Epoch 3/200
11/11 - 0s - loss: 2.4807 - acc: 0.0909
Epoch 4/200
11/11 - 0s - loss: 2.4688 - acc: 0.0909
Epoch 5/200
11/11 - 0s - loss: 2.4570 - acc: 0.2727
Epoch 6/200
11/11 - 0s - loss: 2.4450 - acc: 0.2727
Epoch 7/200
11/11 - 0s - loss: 2.4327 - acc: 0.5455
Epoch 8/200
11/11 - 0s - loss: 2.4200 - acc: 0.5455
Epoch 9/200
11/11 - 0s - loss: 2.4068 - acc: 0.4545
Epoch 10/200
11/11 - 0s - loss: 2.3930 - acc: 0.4545
Epoch 11/200
11/11 - 0s - loss: 2.3784 - acc: 0.3636
Epoch 12/200
11/11 - 0s - loss: 2.3632 - acc: 0.3636
Epoch 13/200
11/11 - 0s - loss: 2.3471 - acc: 0.3636
Epoch 14/200
11/11 - 0s - loss: 2.3300 - acc: 0.3636
Epoch 15/200
11/11 - 0s

Epoch 142/200
11/11 - 0s - loss: 0.3391 - acc: 1.0000
Epoch 143/200
11/11 - 0s - loss: 0.3329 - acc: 1.0000
Epoch 144/200
11/11 - 0s - loss: 0.3268 - acc: 1.0000
Epoch 145/200
11/11 - 0s - loss: 0.3208 - acc: 1.0000
Epoch 146/200
11/11 - 0s - loss: 0.3150 - acc: 1.0000
Epoch 147/200
11/11 - 0s - loss: 0.3093 - acc: 1.0000
Epoch 148/200
11/11 - 0s - loss: 0.3037 - acc: 1.0000
Epoch 149/200
11/11 - 0s - loss: 0.2982 - acc: 1.0000
Epoch 150/200
11/11 - 0s - loss: 0.2928 - acc: 1.0000
Epoch 151/200
11/11 - 0s - loss: 0.2875 - acc: 1.0000
Epoch 152/200
11/11 - 0s - loss: 0.2823 - acc: 1.0000
Epoch 153/200
11/11 - 0s - loss: 0.2772 - acc: 1.0000
Epoch 154/200
11/11 - 0s - loss: 0.2722 - acc: 1.0000
Epoch 155/200
11/11 - 0s - loss: 0.2673 - acc: 1.0000
Epoch 156/200
11/11 - 0s - loss: 0.2624 - acc: 1.0000
Epoch 157/200
11/11 - 0s - loss: 0.2577 - acc: 1.0000
Epoch 158/200
11/11 - 0s - loss: 0.2531 - acc: 1.0000
Epoch 159/200
11/11 - 0s - loss: 0.2485 - acc: 1.0000
Epoch 160/200
11/11 - 0s - l

In [51]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''    
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        result = model.predict_classes(encoded, verbose=0)        
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word    
    sentence = init_word + sentence
    return sentence

In [55]:
print(sentence_generation(model, t, '경마장에', 4))

경마장에 있는 말이 뛰고 있다


In [57]:
print(sentence_generation(model, t, '그의', 2))

그의 말이 법이다


In [61]:
print(sentence_generation(model, t, '가는', 5))

가는 말이 고와야 오는 말이 곱다
